version: '3.8'

services:
  api:
    build:
      context: ../apps/api
    image: scratchbot-api:dev
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_URL: postgres://postgres:example@postgres:5432/postgres
      REDIS_URL: redis://redis:6379

  worker:
    build:
      context: ../apps/worker
    image: scratchbot-worker:dev
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_URL: postgres://postgres:example@postgres:5432/postgres
      REDIS_URL: redis://redis:6379

  ui:
    build:
      context: ../apps/ui
    image: scratchbot-ui:dev
    ports:
      - "8080:3000"
    depends_on:
      - api

  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
